name: Verify Deployment

on: [push]

jobs:
    build:
        name: Compare generated file with existing file
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2

          - name: Installing Hugo
            run: sudo snap install hugo

          - name: Generate Files From Source
            run: hugo -D -d testGeneratedFiles

          - name: Compare Files
            run: diff testGeneratedFiles docs