name: Verify Deployment

on:
    push:
    pull_request:
    schedule:
      - cron: '0 4 * * *'

jobs:
    build:
        name: Compare generated file with existing file
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2

          - name: Installing Hugo
            run: sudo snap install hugo

          - name: Print Hugo Version
            run: hugo version

          - name: Generate Files From Source And Compare
            run: make test
